create table if not exists public.external_car_registrations (
  id bigint generated by default as identity primary key,
  submission_id uuid not null,
  company_name text not null,
  company_type text not null,
  plate_region text not null default '없음',
  plate_middle text not null,
  plate_number text not null,
  car_name text,
  owner_name text not null,
  applicant_name text not null,
  applicant_phone text not null,
  access_zones jsonb not null default '[]'::jsonb,
  master_key_requested boolean not null default false,
  parking_zone_code text,
  display_message_code text,
  memo text,
  car_order integer not null,
  created_at timestamptz not null default now()
);

alter table public.external_car_registrations enable row level security;

drop policy if exists "anon can insert external car registrations" on public.external_car_registrations;

create policy "anon can insert external car registrations"
on public.external_car_registrations
for insert
to anon
with check (true);

create unique index if not exists external_car_registrations_plate_unique_idx
on public.external_car_registrations (plate_region, plate_middle, plate_number);
